-- 過去の新人報告・ブラックリストデータの一括取り込み
-- 実行: npx wrangler d1 execute schedule-db --remote --file=import-past-data.sql
-- acquired_ka / matched_ka は、実行時点のusersテーブルと氏名照合し、該当すれば所属課を自動設定します

-- ===== 新人報告(チェック済み、共有シートより) =====
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('07/11 20:18','吉崎','土地 瞬平','4年生','','二日間通しで入ってくれました。二日目では前日の経験もあってかスムーズに案内していました。',3,7,'もう少し様子見','4回生なので将来性はないが平日の稼働面を見れば取ってもよい気がする','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('土地 瞬平',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('07/11 20:20','吉崎','水口 皇英','3年生','吉崎','初めての現場の中しっかりとミーティングを聞き業務に望んでくれました。表情と明るさがものすごく良かったです。',4,8,'もう少し様子見','3回生なのでチーフは無理でも良いメンツになると思います。他現場での様子をみたいです。','吉崎','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('水口 皇英',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('07/19 23:06','坂本遥希','上田 晴太','1年生','津山','施設巡回やミーティングのしっかり聞いてメモをとろうとする姿勢がよかったです。不明点をしっかり聞いて確認し、規制退場時もお客様へのお声がけを積極的に行ってくれました。',3,6,'あげる','しんどめの大現場で（野外フェス）などに入れながら鍛え、ホール現場で丁寧さを学ばせる→良メンツへ','津山','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('上田 晴太',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('07/20 9:09','津山','星野樹','1年生','','立ち姿勢がきれいで、他メンツと話す様子など人柄の良さを感じます。',4,8,'もう少し様子見','ホール現場で2階席を1人で任せられるようなメンツ→人引っ張る能力が伸びればサブチーフへ','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('星野樹',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('07/20 9:21','津山','上前 奏太','1年生','','無線を持たせてみました。規制退場のときに、混雑状況を見ながらお客様の案内導線を調整しており、賢かったです。',4,8,'あげる','稼働率見込めるため、さまざまな現場を経験させて良メンツに','酒井㊓','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('上前 奏太',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('07/20 9:27','津山','足立 玲','1年生','','Cステまわりでカメラなどが多く通る中、しっかり周りの状況を見て柵の開け閉めができていました。意味のある質問が多く、よく考えながら仕事している印象。',4,7,'あげる','ガッツあるタイプなので搬入術の頭→大現場の良メンツ','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('足立 玲',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('07/20 9:32','坂本','小寺 翔太','1年生','津山','規制のとき、あらかじめレクチャーを入れていたように行動できていた。理解度が高く、一度吹き込めばできてしまうタイプだと思う。',NULL,NULL,'','','','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('小寺 翔太',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('07/21 0:13','津山','小寺 翔太','1年生','','メンツの行動を真似して自発的に行動できるタイプです。大人数を引っ張ることは未知数ですが、やるべきことに対して逃げない点が魅力でした。',4,7,'あげる','メンツとして計算できる（どの現場でもいると助かる）ように育てたいです。','津山','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('小寺 翔太',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('07/21 16:05','岡本','三輪優心','1年生','','以前より自発敵な行動が見られるようになった事が好印象。丁寧な接客が印象的。発見したのは大現場だが、ホールで良さを発揮してくれるのではと思う。',4,7,'あげる','津山手配に所属させ、ホール中心に良メンツとして育成したい。より積極性が見えればチーフも視野か','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('三輪優心',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('07/28 20:29','服部','三谷武人','不明','','受け答えがしっかりしており、分からない点は積極的に聞いてきてくれました。まだ回数が少ないこともあり、慣れたら良いメンツになりそうです。',5,7,'もう少し様子見','良メンツ','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('三谷武人',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('08/01 21:17','岡本','中田 幸佑','不明','吉崎','悪い意味で目を離せない子でした。何かしようとする姿勢は見えましたが、要所要所に変さを感じます。遅刻してきた上に知らぬ間に帰ってました。「ナシ」',NULL,NULL,'','','','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('中田 幸佑',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('08/03 1:07','津山','山路 潤耶','4年生','','お客様に対する声掛けは上手い。ただ時折出る緩さがなめているのかな？と思わせる。',3,4,'却下','4回生ということもあり、各小現場で頑張ってもらうのも手です','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('山路 潤耶',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('08/03 9:22','乾','柿原温','1年生','佐藤','良かった点 ・話を聞く姿勢と受け答えが好印象 ・物事への理解が早く、疑問に思ったことを放置せずすぐ聞いてくれる ・他の新人の子と施設のおさらいとかをしていた。 悪かった点 ・トラメガでの広報をお願いしていたが、あまり慣れていないがために、声が小さくなることや、トラメガを使う頻度が少ないことが伺えた。',NULL,NULL,'','','','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('柿原温',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('08/07 3:06','津山','森 圭吾','3年生','','礼儀正しく、ひとつひとつの行動が丁寧です。自分から何か生み出すことは苦手そうですが、指示に対して100%で返してくれる。',4,6,'もう少し様子見','あと1年早ければチーフに育てられる存在だと感じます。楽屋番など安心して任せられるメンツにしたい。稼働率次第で声かけようと思ってます。','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('森 圭吾',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('08/10 6:40','坂本','谷口 瑠輝','1年生','岡本','ミーティングを聞く姿勢が素晴らしく、不明点があればすぐに聞いてくれました。指示に対しても反応を示して行動してくれました。経験の少なさからぎこちないところがあるので、様子見で上げてます。',4,7,'もう少し様子見','DOI期間中でどんどん良くなってきています。良メンツになる可能性はあるかと。他現場での評判が良ければ獲得を考えます。','岡本','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('谷口 瑠輝',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('08/16 18:55','坂本','小村 司','1年生','岡本','トラメガ広報も他の新人の子と比べて行ってくれた。指示に対する返事もいいが、メンツにあげるならもう少し積極性が欲しいと感じる。',3,5,'もう少し様子見','気の利く子だが、立ち姿勢がいい加減なのが目立ちました。個人的にはナシ','岡本','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('小村 司',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('08/16 23:40','吉崎','幸重 航基','1年生','','ものすごく気がききます。自発的な提案もあり、ものすごく頼りになりました。イレギュラーがかなり起こる中で指示をしなくても臨機応変に対応してくれました。数人まとめることが可能です。',4,9,'あげる','コンサートの両メンツ→チーフも視野','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('幸重 航基',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('08/18 20:29','矢吹','野見山悠','3年生','','暑い中の作業でも嫌な顔ひとつせずにレスポンス良く作業を行ってくれた。しかも、何気ないところも考えてやってくれていて賢さを感じた。京大生で大学院進学予定。シミショウがめっちゃ好きらしい。',3,8,'もう少し様子見','現場回数少ないかつ単純作業だったので未知数だがチーフになれるのでは','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('野見山悠',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('08/26 13:48','髙田','森島一惺','2年生','','自分の仕事を終始全力で行ってくれてるのが非常に印象的で、とてもガッツのある子だと思わされました。現場に対する意欲もあり、どんな仕事でもやりがいを感じてくれてるのが話をしてて伝わりました。コンサート現場にも高い関心を寄せています。',5,8,'あげる','コンサート現場の良メンツ、NAKEDのセクションチーフ','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('森島一惺',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('08/26 17:07','津山','髙橋虎太郎','1年生','','なにより笑顔が素晴らしい。言ったことに対するレスポンスも良く、今後を期待させるような子です。',4,7,'もう少し様子見','まだチームに入るか迷い中とのことで様子見にしてます。サブチーフぐらいになれればなと、','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('髙橋虎太郎',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('08/26 17:10','津山','楪大輝','1年生','','指示に対する理解度が高いです。反応速度が早くなればもっと良くなります。1回生としては良い方。',3,7,'あげる','シンプルなメンツ。上を目指すことを求めすぎず、いろんな仕事ができる子にしたい','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('楪大輝',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('08/30 23:31','高橋慶多','金子聡志','1年生','高田','コミュニケーション能力が高く、教えたことを周りに共有しスムーズに作業をしているのが非常に好印象でした。初めて会った時から声を出すことが出来るし、物覚えが早く積極的に仕事に取り組むのでチーフになれると思いました。',4,8,'あげる','サンガのセクションチーフ。自分で考えて、チーフにも相談できる能力が素晴らしいと思うので、サンガを引っ張ってもらいたい。','髙田','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('金子聡志',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('09/01 21:07','乾','高橋 虎太郎','1年生','連絡無し→現場決まり次第連絡予定','指示への理解が早く、積極的に仕事に取り組んでくれていた。 他の新人の子達を巻き込んで、作業を行ったり他のサボっている子に対して、注意していたところがとても一年生とは思えないくらいしっかりしていた。 松井・佐藤がこの子は良かったという発言もあり、次期チーフとして育てていきたいと思うような子でした。',4,7,'あげる','人をまとめる力があると思われるので、搬入出頭など簡単なところから始めたい。ゆくゆくはサブチーフ、チーフまで育成したいと考えてます。','松井','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('高橋 虎太郎',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('09/18 23:12','津山','酒井航大','2年生','','理解度が高く、自分の考えを持っているところが良い。真面目なタイプで、着実に成長していけるタイプだと感じる',4,8,'あげる','現場にいると助かるような安定したメンツに育成する','津山','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('酒井航大',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('10/04 21:17','坂本','久松優真','2年生','佐藤','静かで真面目なタイプ伝えたことをしっかり遂行できる。少し難しいことをお願いしても意図を汲み取ってこなしてくれました。',NULL,NULL,'','','','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('久松優真',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('10/12 11:33','中山克哉','稲谷航希','4年生','高田','4回生だが院に進むそうです。理解が早く、さぼらない姿勢が良いと思いました。',4,8,'あげる','NAKEDのチーフや、ホール現場の重要ポジにハマりそうだと思うので、大事なところを任せられる良メンツに育てたいです。','髙田','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('稲谷航希',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('10/19 8:04','佐藤','矢野 優心','1年生','','話した時の受け答えがしっかりとしていた様子、1回生で現状稼働率は低く、次の現場も決まっていない状態',5,7,'もう少し様子見','まだ不明','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('矢野 優心',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('10/21 12:26','津山','川北 皓','2年生','','新人としては現場回数も多く、現場を選ばないことから手配社員からの評価高い。仕事に前向きに取り組むところも素晴らしい。',4,7,'あげる','ホールのパッケージ頭','津山','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('川北 皓',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('10/22 17:50','坂本','松田悠暉','1年生','','広報など頼んだことをしっかりしてくれる。人当たりがよく、長時間の現場にも関わらずダレることなく頑張ってくれました。稼働率的に様子見。',3,6,'もう少し様子見','現場経験も少なく未知数ですが、どの現場にいても助かる良メンツになれると思います','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('松田悠暉',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('10/27 17:50','髙田','大地 遥斗','1年生','','明るく優しい雰囲気で、お客さんへの気づかいが素晴らしいと感じた。謙虚で真面目な面持ち合わせていて教え込めば大事なところを任せられる戦力になると感じた。',4,8,'あげる','現場の種類問わずいてくれたら助かるようなサブチーフ','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('大地 遥斗',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('10/30 22:32','武田','大城 奏','1年生','津山','4回生のような風格があり、非常に落ち着いた印象です。指示に対して的確に取り組んでくれ、不明点は解決しようとする姿勢も評価できます。',4,7,'あげる','オールラウンダーサブチ','津山','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('大城 奏',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('11/02 15:25','石束','河本壮太朗','1年生','','入り口前で各部の広報をお願いしたのですがハキハキと広報してくれました。受け答えもしっかりとしていて理解力もあります。業務に対しての意欲も高いです。',5,8,'あげる','サッカー(出来ればガンバ)のセクションチーフから始めてほしい','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('河本壮太朗',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('11/03 19:05','乾','布施田 和真','不明','してない','愛想が悪く、立ち姿勢等も雑であることが伺える。生意気な態度をとってくることがある。 広報で声を出せない、そもそもほとんど言ってない等様々な悪かった点が見受けられました。',NULL,NULL,'','','','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('布施田 和真',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('11/03 19:13','吉崎','谷山 夢斗','3年生','','メンツなのかと勘違いするほど落ち着いて仕事をしていました。また視野も広く周りを見て広報内容を考えたりとかなり良い動きを見せてくれました。',4,8,'もう少し様子見','良メンツ','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('谷山 夢斗',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('11/03 19:17','佐藤','岡本 洸音','不明','','返答からレクチャー等の内容を理解していると思わせる言動が見られた',4,8,'もう少し様子見','言動は良かったが、あまり彼の動きを見れていないので見た上で獲得に踏み込みたい','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('岡本 洸音',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('11/18 23:19','津山','正垣快斗','2年生','','元気があって、しんどい仕事から逃げないタイプ。準備日から入ってくれていて、平日の稼働率も期待できる。',4,7,'あげる','良メンツ','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('正垣快斗',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('11/24 12:08','坂本','池田 義知','3年生','','広報や遅れ客の案内を積極的に行っていて好印象。人当たりもよく受け答えもしっかりしてました。3回生で、大きな稼働率も見込めなさそうなので様子見です。',4,6,'もう少し様子見','どの現場にいても助かる良メンツ','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('池田 義知',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('11/28 2:21','津山','大角 哲平','1年生','','真面目で賢いタイプです。指示に対して100点で返してくれ、安心安全という印象。',4,8,'あげる','ハマればチーフ','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('大角 哲平',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('11/30 15:53','髙田','長内拓磨','1年生','','やることはきっちりやる印象があり、1回生ながら落ち着きがある性格にみえる',4,7,'あげる','コンサートの種類問わず活躍してくれるオールラウンダー、NAKEDのチーフ','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('長内拓磨',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('11/30 15:58','髙田','戸田蓮','1年生','','コミュニケーション能力、お客さんの対応、無線の使い方に光るものを感じた。稼働率もなかなかのもので、来月までに20回目指してといったら、今月には達成しそうな勢いであった。',5,9,'あげる','NAKEDのチーフ、ホール現在などのチーフをさせてみたい','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('戸田蓮',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_chief,first_note,s_motivation,s_total,draft,plan,checker,status,acquired_ka) VALUES ('03/22 11:33','佐藤','林 汰一','2年生','','アーティスト物販の最後尾を任せていたが、自分が見れていなくても、長い列の蛇行を綺麗に組んでいた。片付け時も空気を読んで柵を固めたりなど率先してやってくれていた。新3回生で今後続けるかは曖昧、',4,8,'もう少し様子見','良メンツ','','checked',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('林 汰一',' ',''),'　','') LIMIT 1),''));

-- ===== 新人報告(1次報告のみ、Forms回答シートより) =====
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_note,status,acquired_ka) VALUES ('07/13','佐藤→ガンバ班(國分)','林 汰一','3年生','[発見現場:キュウソネコカミ@INTEX / 現場回数:5回以下] アーティスト物販の最後尾を任せていたが、自分が見れていなくても、長い列の蛇行を綺麗に組んでいた。片付け時も空気を読んで柵を固めたりなど率先してやってくれていた。新3回生で今後続けるかは曖昧、','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('林 汰一',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_note,status,acquired_ka) VALUES ('07/13','髙田','宮橋祐輔','2年生','[発見現場:AMEX@醍醐寺 / 現場回数:20回越え] コミュニケーション能力があり、接客態度も非常に良かったです。固定配置でしたが、段差のあるところを一人一人に下から上まで案内してあげていたところに惹かれました。','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('宮橋祐輔',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_note,status,acquired_ka) VALUES ('07/13','髙田','水流諒晴','3年生','[発見現場:GRANRODEO・NHK大阪 / 現場回数:5回以下] 初現場でロビー間仕切りの配置でしたが、立ち姿勢もよく、スタッフさんへの挨拶を欠かさず行っていたことが好印象','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('水流諒晴',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_note,status,acquired_ka) VALUES ('07/13','津山','佐々木優斗','フリーター','[発見現場:恐怖心展@イベントラボ / 現場回数:20回越え] フリーターで嘱託契約を結んでいることもあり稼働率重視でとります。社会人経験ありで、コミュニケーションも問題ない。','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('佐々木優斗',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_note,status,acquired_ka) VALUES ('07/13','髙田','稲田智之','2回生','[発見現場:恐怖心展@イベントラボ / 現場回数:10回程度] 非常に誠実で、しんどいことからも逃げないタイプです。会場のゴミを拾ったりと気が利く面もあります。','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('稲田智之',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_note,status,acquired_ka) VALUES ('07/13','坂本','古賀寛人','2回生','[発見現場:嵐@KDO / 現場回数:10回程度] ミーティングをしっかり聞くことや指示をしっかり聞いて行動に移すことができメンツとしての伸び代を感じるが、真面目すぎるとも思うタイプの子。','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('古賀寛人',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_note,status,acquired_ka) VALUES ('07/13','津山','小西瑛士','4回生','[発見現場:嵐ロビデコ@グラングリーン / 現場回数:20回越え] 広報の仕方や業務への姿勢など、メンツとしての素質が十分備わっている。4回生ですが、稼働率を見込めるため獲得希望です。','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('小西瑛士',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_note,status,acquired_ka) VALUES ('07/13','津山','大地遥斗','2回生','[発見現場:音道楽@GLION / 現場回数:10回程度] 真面目なタイプで静かな印象ですが、お客様へ寄り添うような案内の仕方をしていて丁寧な子だと感じました。','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('大地遥斗',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_note,status,acquired_ka) VALUES ('07/13','佐藤','西部 翔琉','3回生','[発見現場:B''z@OCC / 現場回数:20回越え] 城ホの物販で入り口に2日間ついてもらっていたが，丁寧な対応と広報もしてくれていた．現場回数は多いがチームのシステムがわかっていなくてこれまで入っていなかった．これから辞めるつもりもないみたい．','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('西部 翔琉',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_note,status,acquired_ka) VALUES ('07/13','坂本','伊谷渉真','不明','[発見現場:メトロック / 現場回数:5回以下] メトロック入口で入ってた子です。客出し中と片付けのときに指示に対する理解力が高かった。業務にも協力的でテキパキ動くタイプ。落ち着いて話す時間を取れず、学年の確認やLINE交換まではできずです、','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('伊谷渉真',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_note,status,acquired_ka) VALUES ('07/13','髙田','湯谷亮洋','1回生','[発見現場:音道楽@GLION / 現場回数:10回程度] ミーティングを聞く姿勢が他の人とは違いました。業務に関しても分からないことは質問してくれたり、コミュニケーションもしっかり取れたりと、自分の中で物事を考えて仕事をしてくれてます。','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('湯谷亮洋',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_note,status,acquired_ka) VALUES ('07/13','髙田','林汰一','3回生','[発見現場:M1@GLION / 現場回数:10回程度] 最前管理をしていましたが、通りかかるスタッフさんへの挨拶を欠かさず、椅子バラ後の片付けにも率先して自分で動き、分からないことは都度聞いてくれて丁寧だと感じた。院進予定で将来性もある。','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('林汰一',' ',''),'　','') LIMIT 1),''));
INSERT INTO reports (ts,reporter_name,candidate_name,candidate_grade,first_note,status,acquired_ka) VALUES ('07/13','津山','中谷陽斗','2回生','[発見現場:NiziU@ドーム / 現場回数:20回越え] 昨年末からずっと目を付けていた子です。愛想が良く、メリハリをつけて仕事ができる子だと思います。チームに入る意欲が出てきているため、絶対とります。','pending',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('中谷陽斗',' ',''),'　','') LIMIT 1),''));

-- ===== ブラックリスト =====
INSERT INTO blacklist (ts,date,reporter,name,s_talk,s_dress,s_groom,s_late,s_work,reason,added_by,matched_ka) VALUES ('10/29','10/29','相尾','熊谷 拓真',2,4,4,2,4,'挙動不審な印象。受け答えははきはきしているが、慌ただしい。 遅刻癖がある。バスで来るため遅延が多い。言い訳にならないとは自分で言うているものの直らない。 追記:メガネの子？この子はダメやと思います（佐藤）一生懸命だが、あかん(？)','相尾',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('熊谷 拓真',' ',''),'　','') LIMIT 1),''));
INSERT INTO blacklist (ts,date,reporter,name,s_talk,s_dress,s_groom,s_late,s_work,reason,added_by,matched_ka) VALUES ('10/28','10/28','相尾','和田 空大',3,2,3,3,2,'スーツで白靴下着用。客止めの内止めもできない。 客だし終わった後に片付けもせず、舞台の搬出に混ざろうとする。（理由：みんながいるから）','相尾',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('和田 空大',' ',''),'　','') LIMIT 1),''));
INSERT INTO blacklist (ts,date,reporter,name,s_talk,s_dress,s_groom,s_late,s_work,reason,added_by,matched_ka) VALUES ('10/30','10/30','酒井','遠山 暖大',3,3,2,4,2,'ネイキッドで発見。基本誰にでもタメ語ベースで、失礼な印象。ジャンパーが小さいのか、ジッパー全開に何度注意してもしてしまう。また、「そこのライト付いてる看板運んで」と言う指示で、ベンチを運ぼうとする。根本何も考えていない。間仕切りなどのポジションも危うい印象を受けた。','酒井',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('遠山 暖大',' ',''),'　','') LIMIT 1),''));
INSERT INTO blacklist (ts,date,reporter,name,s_talk,s_dress,s_groom,s_late,s_work,reason,added_by,matched_ka) VALUES ('11/3','11/3','佐藤','田中 恭一',3,4,3,2,3,'Ballet Muses@東大阪で発見。遅刻から始まり、休憩時も時間通りに戻って来れない。その事について聞くと「ほんまっすか」みたいな感じ。','佐藤',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('田中 恭一',' ',''),'　','') LIMIT 1),''));
INSERT INTO blacklist (ts,date,reporter,name,s_talk,s_dress,s_groom,s_late,s_work,reason,added_by,matched_ka) VALUES ('11/18','11/18','佐藤','河合 飛佳',3,3,2,4,2,'ネイキッドで発見。自分が横にいる時でも柵に寄りかかったり手をついたり落ち着きがない。指示した内容も全く頭に入ってない。現場回数は50回以上と多いものの接客業をする上でかなり欠けている部分が多い気がする。','佐藤',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('河合 飛佳',' ',''),'　','') LIMIT 1),''));
INSERT INTO blacklist (ts,date,reporter,name,s_talk,s_dress,s_groom,s_late,s_work,reason,added_by,matched_ka) VALUES ('12/1','12/1','佐藤','山口 和也',2,2,3,2,3,'自身がビーイングやっていてワースト3に入るくらいの人物。現場回数50弱にも関わらず、ジャージ,ロゴ入り,グレーズボンで遅刻してきて、タメ口混じりの敬語。こりゃダメ','佐藤',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('山口 和也',' ',''),'　','') LIMIT 1),''));
INSERT INTO blacklist (ts,date,reporter,name,s_talk,s_dress,s_groom,s_late,s_work,reason,added_by,matched_ka) VALUES ('12/20','12/20','津山','中村 玲勇',2,4,4,4,2,'間仕切りレクチャーしっかりやりましたが、楽屋に客を入れて問題になりました。事情聴取時、「誰でも入れていいよと言われました」と謎発言されました。話が通じない子です。クソです','津山',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('中村 玲勇',' ',''),'　','') LIMIT 1),''));
INSERT INTO blacklist (ts,date,reporter,name,s_talk,s_dress,s_groom,s_late,s_work,reason,added_by,matched_ka) VALUES ('12/20','12/20','津山','藤本 蒼士',3,4,3,4,2,'レクチャー時から舐めた態度を取った後、間仕切りで足を組む。社員に見つかった際も足を直そうとしなかったことから、仕事をしているという意識が皆無だと思われます。','津山',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('藤本 蒼士',' ',''),'　','') LIMIT 1),''));
INSERT INTO blacklist (ts,date,reporter,name,s_talk,s_dress,s_groom,s_late,s_work,reason,added_by,matched_ka) VALUES ('12/20','12/20','津山','長友 一馬',2,3,4,4,2,'女性無線持ちがロビーにいといてと言ったのに勝手にどこかへ行き、勝手に迷子になっていました。その女の子はアイツ話通じひん、ほんまにNGで、だそうです。','津山',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('長友 一馬',' ',''),'　','') LIMIT 1),''));
INSERT INTO blacklist (ts,date,reporter,name,s_talk,s_dress,s_groom,s_late,s_work,reason,added_by,matched_ka) VALUES ('1/9','1/9','酒井','市田 拓海',2,4,4,4,2,'シンプルにやってと言っていることができない。頭も悪い。何を考えているかわからない。30年後街中で急に大声出す奴になりそう。','酒井',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('市田 拓海',' ',''),'　','') LIMIT 1),''));
INSERT INTO blacklist (ts,date,reporter,name,s_talk,s_dress,s_groom,s_late,s_work,reason,added_by,matched_ka) VALUES ('1/11','1/11','佐藤','狩峰 遥仁',2,4,4,4,2,'JUMP＠KDOで発見、EV間仕切り配置だったが勤務設定時間になったら勝手に控室に戻る（理由：勤務設定時間過ぎて忘れられてると思ったから←開演中に2回も休憩回したにも関わらず） 現場回数20回くらいなのにチーフ,控室管理に名前も言わないで勝手に帰った→会社から本人に連絡してもらってドームに帰還させた ミーティング中も全く関係ない方向を向いたり、直接話した際も何を言ってるのかわからない','佐藤',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('狩峰 遥仁',' ',''),'　','') LIMIT 1),''));
INSERT INTO blacklist (ts,date,reporter,name,s_talk,s_dress,s_groom,s_late,s_work,reason,added_by,matched_ka) VALUES ('1/18','1/18','岡本','西田 凌',4,2,2,3,4,'香西かおり@テクスピア大阪で発見。現場回数80回以上にも関わらず、スニーカーソックス着用してるだけでなく黒スニーカーでいいと思い込んでいた。20秒に1回ぐらい大あくびしていて印象も悪い。人前に出せない子です。','岡本',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('西田 凌',' ',''),'　','') LIMIT 1),''));
INSERT INTO blacklist (ts,date,reporter,name,s_talk,s_dress,s_groom,s_late,s_work,reason,added_by,matched_ka) VALUES ('1/26','1/26','坂本','無量井 翔平',3,4,4,4,2,'1/26キンプリ@KDOで発見。座席の案内もあやふや。開演中に方杖をついて座っていた。間仕切り配置でも不安な印象。','坂本',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('無量井 翔平',' ',''),'　','') LIMIT 1),''));
INSERT INTO blacklist (ts,date,reporter,name,s_talk,s_dress,s_groom,s_late,s_work,reason,added_by,matched_ka) VALUES ('2/1','2/1','坂本','六信 怜士',3,3,3,4,2,'なにわ@KDOで発見。開演中、足を広げ柵にもたれかかって座っている。何度注意しても目を離したらすぐ足を広げる。マスクを鼻出しでつけており、注意しても、外すなり、しっかり着用するなりができない。名札台紙も白黒のモノを使用しており、指摘されるまで違和感を感じていなかった。 立ち姿勢もすぐダレ、終演後も急に通り合わせ部隊から抜けるなど、案内業務以外にも危うさを感じた。','坂本',COALESCE((SELECT ka FROM users WHERE REPLACE(REPLACE(name,' ',''),'　','')=REPLACE(REPLACE('六信 怜士',' ',''),'　','') LIMIT 1),''));
